export enum ErrorCode {

  BAD_REQUEST = "BAD_REQUEST",

  NOT_FOUND = "NOT_FOUND",

  UNAUTHORIZED = "UNAUTHORIZED",

  FORBIDDEN = "FORBIDDEN",

  RATE_LIMITED = "RATE_LIMITED",

  INTERNAL_ERROR = "INTERNAL_ERROR",

  UNKNOWN_ERROR = "UNKNOWN_ERROR"

}